apiVersion: v1
kind: Secret
metadata:
 name:
  {{ include "database.fullname" . }}-secret
type: Opaque
stringData:
 MYSQL_DATABASE:
  {{ .Values.mysql.database }}
 MYSQL_USER:
  {{ .Values.mysql.username }}
 MYSQL_PASSWORD:
  changeMe
 MYSQL_ROOT_PASSWORD:
  rootChangeMe
