replicaCount: 1
image:
 repository: mysql
 tag: "8.0"
 pullPolicy: IfNotPresent
service:
 type: ClusterIP
 port: 3306
mysql:
 database: paymentology
 username: paymentology
storage:
 enabled: true
 size: 50Gi
 storageClass: gp3
resources:
 requests:
  cpu: 500m
  memory: 1Gi
 limits:
  cpu: 1
  memory: 2Gi
securityContext:
 runAsNonRoot: false
 fsGroup: 999
backup:
 enabled: true
 schedule: "0 2 * * *"
