apiVersion: v1
kind: ConfigMap
metadata:
  name:
    {{ include "product-service.fullname" . }}-config
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profile | quote }}
  DB_URL: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
 